#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

# This file contains the arguments of the pipeline for functional verification of LSPE-STRIP (2023)
# September 29th 2023, Brescia (Italy)

[official_pipeline_args]

########################################################################################################################
# Positional Arguments (mandatory)
########################################################################################################################
subcommand = 'tot'
path_file = '../data_test'
start_datetime='2023-02-22 00:00:00'
end_datetime='2023-02-22 00:30:00'
name_pol='B0'

########################################################################################################################
# Flags (optional)
########################################################################################################################

# TS Analysis
thermal_sensors = "false"
ts_sam_exp_med=60.0
ts_sam_tolerance=1.0

# HK Analysis
housekeeping = "true"
hk_sam_exp_med = "1.4, 1.4, 10.0"
hk_sam_tolerance = "0.1, 0.1, 0.5"

# Correlation Analysis
corr_plot= "false"
corr_mat="false"
cross_corr="false"
corr_t=0.4

# Scientific Analysis
even_odd_all='A'
scientific="false"
rms="false"
smooth=1
window=2
sam_tolerance=0.005

# Spectral Analysis
fourier="false"
nperseg=256
nperseg_thermal=256

# Spike Analysis
spike_data="false"
spike_fft="false"

# Output dir for plots and reports
output_plot_dir='../plot'
output_report_dir='../plot/Reports'