# -*- encoding: utf-8 -*-

# This file contains the arguments of the pipeline for functional verification of LSPE-STRIP (2023)
# December 29th 2023, Brescia (Italy) -

[official_pipeline_args]

########################################################################################################################
# Positional Arguments (mandatory)
########################################################################################################################
subcommand = 'pol_hk'
path_file = '../data_test'
start_datetime='2023-03-13 00:00:00'
end_datetime='2023-03-13 03:00:00'
name_pol= "all" # Set 'all' to parse all 55 polarimeters

########################################################################################################################
# Flags (optional)
########################################################################################################################

# TOML
toml_file_path = "config/validation_config/config_pol_hk.toml"

# HK Analysis
hk_sam_exp_med = "1.4, 1.4, 60.0"
hk_sam_tolerance = "0.1, 0.1, 0.5"

# Correlation Analysis
corr_plot= "true"
corr_mat= "true"
corr_t=0.4

# Output dir for plots and reports
output_plot_dir='../plot'
output_report_dir='../plot/Reports'
report_to_plot ='../..'
